"""Custom settings generated by Skaffold."""

import os
import settings

settings.INSTALLED_APPS += {{{ apps }}}

# Static files for your app.
# docs.djangoproject.com/en/1.8/ref/settings/#std:setting-STATICFILES_DIRS
# for more examples on **multiple** app directories and configuration.
PROJECT_DIR = os.path.abspath(os.path.dirname(__file__)) + '/{{{ app_name }}}/'
STATIC_ROOT = PROJECT_DIR + '{{{ static_root }}}'
MEDIA_ROOT = STATIC_ROOT + '{{{ media_root }}}'
